### ISSUE TITLE
Running a dedicated instance

### ISSUE THREAD

**Issue by bertagknowles** [fofr/cog-comfyui#128]
My json is running successfully. Now I want to run this workflow in a dedicated cog instance to skip queue time and improve performance. I want to include only the models and custom nodes that are used in the workflow. Can I include the models and custom nodes in the image file that is pushed to replicate so that they are not downloaded again and again. Any detailed guide on how to implement this would be helpful. Thanks.

**Comment by fofr** [comment]
Downloading the weights is faster than baking them into the container, this is because we can download weights more aggressively (in parallel from a hot cache using multiple connections) as opposed to docker container layers which load more slowly (it's counterintuitive but it's the fastest)

As for a dedicated instance, couple of choices:

## 1. Simplest – make a deployment of the model

https://replicate.com/deployments/create

<img width="1082" alt="Screenshot 2024-07-18 at 12 09 50" src="https://github.com/user-attachments/assets/4d0ad47b-fbff-4edc-9318-b4170fec84c6">

## 2. Fork this repo and push your own cog image

Uou can then make sure weights are downloaded during setup rather than at predict time (this is still faster than putting them in the container). You'll need to do this on a GPU. There are good guides here:

- https://cog.run/getting-started-own-model/
- https://cog.run/deploy/

This is an example of how I've done that:

https://github.com/fofr/cog-comfyui-kolors

You can also run the script `scripts/prepare_template.py` to remove a lot of the code needed for a generic JSON model and replace it with a predict.py file that works from a fixed JSON file and modifies just the values within that file. ([Example of that that does](https://github.com/fofr/cog-comfyui-kolors/commit/531159dc777a63dcef5f2affa24d506caac37b9c)

## 3. Make a "training" of any-comfyui-workflow

This is simple but also a little bit hacky. You can visit the `train` tab and generate your own new comfyui model that's exactly the same as the one you've been using, but it'll be your personal one.

https://replicate.com/fofr/any-comfyui-workflow/train

You'll need to include some weights from HuggingFace or CivitAI that you want to use there (they'll get downloaded, bundled up and then loaded from our fast cache during setup at point of use)

---

Let me know how you get on. There's still lots of work to do to make this easier.

**Comment by bertagknowles** [comment]
Thanks for the guide. I didn't know that downloading is faster than baking them. While running workflows I find variations in the time it takes for the same model to download. Sometimes it takes 3 seconds while at other times it takes 16 seconds. 
I find deployments to be the easiest but I don't want to be billed for idle time and setup time. The second option is good but little complex. Maybe I'll go with the deployment if I am unable to push a working modified cog or train one. 

How do I ensure that the weights are downloaded during setup rather than at predict time. Going by the example (https://github.com/fofr/cog-comfyui-kolors) Does the code below download the models during setup?
--------------------
        self.comfyUI.handle_weights(
            {},
            weights_to_download=[
                "checkpoints/chatglm3-fp16.safetensors",
                "Kolors",
                "sdxl_vae.safetensors",
            ],
        )
---------------------

**Comment by bertagknowles** [comment]
ok..will try it out...thanks

**Comment by bertagknowles** [comment]
Hi fofr, I have create an instance using the 3rd option: Make a "training" of any-comfyui-workflow. I added the link to the checkpoint model from HuggingFace. Now when I run the instance, it runs successfully and the checkpoint model is not downloaded as it already exists in the directory. However other models are downloaded as there wasn't any option to place the url's during training. The training was successful.

Now when running workflows, I noticed that occasionally it forgets to download some models and the run fails. I need to wait for the instance to become "cold" and when it boots again then prediction is successful. Why does this happen and can I place all the required models during training somehow? 

Prediction failed.

segm/face_yolov8n-seg2_60.pt unavailable. View the list of available weights: https://github.com/fofr/cog-comfyui/blob/main/supported_weights.md

Checking weights
✅ Realistic_Vision_V6.0_NV_B1_inpainting_fp16.safetensors exists in ComfyUI/models/checkpoints
⏳ Downloading CLIP-ViT-H-14-laion2B-s32B-b79K.safetensors to ComfyUI/models/clip_vision
✅ CLIP-ViT-H-14-laion2B-s32B-b79K.safetensors downloaded to ComfyUI/models/clip_vision in 1.63s, size: 2411.24MB
⏳ Downloading bbox/hand_yolov8s.pt to ComfyUI/models/ultralytics/bbox
✅ bbox/hand_yolov8s.pt downloaded to ComfyUI/models/ultralytics/bbox in 0.11s, size: 21.44MB
⏳ Downloading bbox/face_yolov8m.pt to ComfyUI/models/ultralytics/bbox
✅ bbox/face_yolov8m.pt downloaded to ComfyUI/models/ultralytics/bbox in 0.13s, size: 49.59MB
Traceback (most recent call last):
File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/cog/server/worker.py", line 221, in _predict
result = predict(**payload)
File "/src/predict.py", line 105, in predict
wf = self.comfyUI.load_workflow(workflow_json or EXAMPLE_WORKFLOW_JSON)
File "/src/comfyui.py", line 218, in load_workflow
self.handle_weights(wf)
File "/src/comfyui.py", line 92, in handle_weights
self.weights_downloader.download_weights(weight)
File "/src/weights_downloader.py", line 45, in download_weights
raise ValueError(
ValueError: segm/face_yolov8n-seg2_60.pt unavailable. View the list of available weights: https://github.com/fofr/cog-comfyui/blob/main/supported_weights.md

**Comment by bertagknowles** [comment]
I am trying method 2 now. I think I'll fork "https://github.com/fofr/cog-comfyui-kolors" and then modify predict.py, workflow_api.json, custom_nodes.json and try to push it without running it as I don't have a powerful gpu. Hopefully it works.

**Comment by bertagknowles** [comment]
I was able to push cog successfully. I pushed all the models in the container itself. You were right as the starting (loading) time increased to about 3 minutes but the predict time decreased to 5 seconds. I then used A100 (80gb) GPU but the loading time was still 2 minutes. So downloading during setup is still ok. Decreasing the loading time to less than 30 seconds would be awesome.
