### ISSUE TITLE
Versioned Releases to Replicate.com?

### ISSUE THREAD

**Issue by ansonkao** [fofr/cog-comfyui#132]
Have you considered releasing each new version as a separate "model" on replicate? Then developers can test before updating, instead of just hoping it doesn't break randomly while asleep.

Background: Just discovered this repo on Replicate.com. Would love to migrate over to it to take advantage of the pooling and warm boots, but there's a dealbreaker: it seems there's no way to lock down the version.

**Comment by ansonkao** [comment]
Wait a second - I think this might be built into replicate...

<img width="1324" alt="Screenshot 2024-07-24 at 11 32 49 AM" src="https://github.com/user-attachments/assets/321699f9-1d1a-4b0c-b6d4-1110be22424a">

Why then do your docs say this?

<img width="866" alt="image" src="https://github.com/user-attachments/assets/edd35ad7-9859-44d4-91a9-b371e13bd783">

Are you referring to how a lot of the python within the comfyui ecosystem is written to git pull from master?

**Comment by fofr** [comment]
This model currently updates versions so they point to the latest, see this screenshot:

<img width="1070" alt="Screenshot 2024-07-24 at 17 15 58" src="https://github.com/user-attachments/assets/c06aff88-ba81-4019-b064-dadb9d27d63d">

This prevents an issue where a lot of traffic gets spread across many versions and GPUs, which is inefficient.

The docs recommend ways to fix your own version because of this.

**Comment by fofr** [comment]
This model currently updates versions so they point to the latest, see this screenshot:

<img width="1059" alt="Screenshot 2024-07-24 at 17 17 51" src="https://github.com/user-attachments/assets/7cd1d4f6-2e2a-45ab-9e8f-6208c061cdd7">


This prevents an issue where a lot of traffic gets spread across many versions and GPUs, which is inefficient.

The docs recommend ways to fix your own version because of this.

**Comment by ansonkao** [comment]
Gotcha, thanks. Too bad - it would be great to have the best of both worlds. Maybe in a few more months there will be enough traffic that it stays warm 24/7 across multiple consecutive versions.

ComfyUI on Google Trends:
<img width="663" alt="image" src="https://github.com/user-attachments/assets/d88fa0f6-ac23-4bd1-a356-e42047afbc74">
