### ISSUE TITLE
How can I add more weights and custom nodes myself?

### ISSUE THREAD

**Issue by offchan42** [fofr/cog-comfyui#35]
First of all, I would like to say that this project is wonderful.
But I think it's unsustainable to expect the repo maintainer to keep adding more weights and custom nodes as requested by users.

Is there a document describing how to add custom weights and nodes?
If there aren't, it'd be great if you can write it.

Before writing the document, I also appreciate if you explain briefly how to add custom weights and nodes here. Thanks!

**Comment by fofr** [comment]
Hey, good idea.

## Custom nodes

The short version on adding custom nodes

- add any missing dependencies to cog.yaml: https://github.com/fofr/cog-comfyui/blob/main/cog.yaml#L7 (ie check requirements.txt of the custom node you want to use, then add them to the yaml file if they aren't there) – more about that YAML file here: https://cog.run/yaml/
- add the custom nodes you want here, then run the script: https://github.com/fofr/cog-comfyui/blob/main/scripts/clone_plugins.sh#L9-L33
- optional: push the model to Replicate with `cog push`

Caveat: Some custom nodes do on demand downloading of model weights themselves – you might be ok with this, but in the repo I've tried to remove all external dependencies – this is where it gets a bit more complex.

Simple PR example: https://github.com/fofr/cog-comfyui/pull/20
Complex PR example where I had to do work to make the nodes work properly in a docker env: https://github.com/fofr/cog-comfyui/pull/22

## Weights

- if you need to add custom weights, you can download them to the appropriate directory, if you plan to push these weights to Replicate (or somewhere else) you'll need to update the .dockerfile to not ignore them (https://github.com/fofr/cog-comfyui/blob/main/.dockerignore) – this is the simplest way to add weights, but is different to how I do it – simply because I have access to Replicate’s CDN for serving weights
- you could also host your weights somewhere and download them on demand, like AWS or using https://github.com/huggingface/hf_transfer to download fast from HuggingFace

**Comment by drommerkiller** [comment]
I tried to follow your instructions but when building the cog it gives this error:
`WARNING: current commit information was not captured by the build: failed to read current commit information with git rev-parse --is-inside-work-tree
ERROR: failed to solve: error from sender: failed to xattr ComfyUI/custom_nodes/ComfyUI-AnimateDiff-Evolved/models/._AnimateLCM_sd15_t2v.ckpt: operation not permitted

View build details: docker-desktop://dashboard/build/desktop-linux/desktop-linux/tnc1amkgntnm9e2we10egnrj8
ⅹ Failed to build Docker image: exit status 1`

This is what i did: forked the repo an git cloned that.
I edited the .dockerignore file and commented out these:
#*.ckpt
#*.safetensors
# ComfyUI/custom_nodes/ComfyUI-AnimateDiff-Evolved/models
# ComfyUI/custom_nodes/ComfyUI-AnimateDiff-Evolved/motion_lora

I added new custom nodes to list and ran the clone_plugins script.
Then i placed two .safetensors models to checkpoints, AnimateDiff lora and few motion loras to LORAs folder and AnimateLCM_sd15_t2v.ckp to the AnimateDiff models folder.

My workflow is based on running AnimateDiff with LCM models and there is few utility etc custom nodes.

As said, when i run cog push to build the file and push to replicate to my own page, i get that error.

I'm a complete newbie with this, so my in my first try i managed to push the  model to replicate, but it was 1:1 with the original. So that part should work. I followed the instructions on the replicate docs. (i dont have gpu, so i cant test locally.

All help is welcomed!

**Comment by drommerkiller** [comment]
> Hey, good idea.
> 
> ## Custom nodes
> The short version on adding custom nodes
> 
> * add any missing dependencies to cog.yaml: https://github.com/fofr/cog-comfyui/blob/main/cog.yaml#L7 (ie check requirements.txt of the custom node you want to use, then add them to the yaml file if they aren't there) – more about that YAML file here: https://cog.run/yaml/
> * add the custom nodes you want here, then run the script: https://github.com/fofr/cog-comfyui/blob/main/scripts/clone_plugins.sh#L9-L33
> * optional: push the model to Replicate with `cog push`

That does not seem to work. I did all that and pushed model to replicate to my model page, but it does not find any if the custom nodes that i added before running the cog script. Nor does any of the checkpoints be added as it still tries to find them from where the rest are. Adding direct links to models does not work either as they are not "in the list". 

Any pointers beyond that how to mod this to get own custom_nodes and checkpoints?

**Comment by DrakenZA** [comment]
Im also having an issue with this.

I put aniverse_thxEd14Pruned.safetensors inside comfyui/models/checkpoints before making the cog, and i removed the .safetensors and model dir dockerignore entries. But Weights_downloader complains they are not on the list.

**Comment by Lalimec** [comment]
maybe you should also remove "ComfyUI/models" from the list as well.

**Comment by bluematter** [comment]
Couldnt you just add a custom map where we can rewrite the key with full path?

`    def _generate_weights_map(self, keys, dest):
        custom_weights = {
            "zavychromaxl_v31.safetensors": "https://weights.replicate.delivery/default/basedlabs-media/zavychromaxl_v31.safetensors.tar",
            "kitty.safetensors": "https://weights.replicate.delivery/default/basedlabs-media/kitty.safetensors.tar",
            "rife47.pth": "https://weights.replicate.delivery/default/basedlabs-media/rife47.pth.tar",
            "svd_xt_1_1.safetensors": "https://weights.replicate.delivery/default/basedlabs-media/svd_xt_1_1.safetensors.tar",
            # "nightvisionXLPhotorealisticPortrait_v0791Bakedvae.safetensors": "https://storage.googleapis.com/basedlabs-media/nightvisionXLPhotorealisticPortrait_v0791Bakedvae.safetensors.tar",
            # "XL_VAE_C1.safetensors": "https://storage.googleapis.com/basedlabs-media/XL_VAE_C1.safetensors.tar",
            # "pixelArtDiffusionXL_pixelWorld.safetensors": "https://storage.googleapis.com/basedlabs-media/pixelArtDiffusionXL_pixelWorld.safetensors.tar",
            # "ral-dissolve-sdxl.safetensors": "https://storage.googleapis.com/basedlabs-media/ral-dissolve-sdxl.safetensors.tar",
            # "ral-frctlgmtry-sdxl.safetensors": "https://storage.googleapis.com/basedlabs-media/ral-frctlgmtry-sdxl.safetensors.tar",
            # "ral-elctryzt-sdxl.safetensors": "https://storage.googleapis.com/basedlabs-media/ral-elctryzt-sdxl.safetensors.tar",
            # "EldritchComicsXL1.2.safetensors": "https://storage.googleapis.com/basedlabs-media/EldritchComicsXL1.2.safetensors.tar",
            # "ral-vlntxplzn-sdxl.safetensors": "https://storage.googleapis.com/basedlabs-media/ral-vlntxplzn-sdxl.safetensors.tar",
            # "ral-bling-sdxl.safetensors": "https://storage.googleapis.com/basedlabs-media/ral-bling-sdxl.safetensors.tar",
            # "ral-glydch-sdxl.safetensors": "https://storage.googleapis.com/basedlabs-media/ral-glydch-sdxl.safetensors.tar",
            # "ral-polygon-sdxl.safetensors": "https://storage.googleapis.com/basedlabs-media/ral-polygon-sdxl.safetensors.tar",
            # "Particles_Style_SDXL.safetensors": "https://storage.googleapis.com/basedlabs-media/Particles_Style_SDXL.safetensors.tar",
        }

        return {
            key: {
                "url": custom_weights[key] if key in custom_weights else f"{BASE_URL}/{dest}/{key}.tar",
                "dest": f"{BASE_PATH}/{dest}"
            }
            for key in keys
        }`

**Comment by drommerkiller** [comment]
I have now tried everything and there seems to be no way to add more models or nodes. No matter what you have in the cog image, it will always load every node and model from replicate. No matter if you edit the weighs.json and add new model names there, that is not the file what it reads as adding model names to that will not carry on to replicate.

Fofr has given good instructions how to reduce and remove nodes and models to create custom model, but that does not help as we need to add models.

This is now more important than ever as Replicate still has cache loading issues. It just downloaded 120mb motion lora file for two minutes. That motion lora was in the cog model i pushed, but it just ignored it. I have my own motion loras that i want to use but have not found any way to do that. Add to model and get error, add direct link and get error.

How  to edit weights.json so it will not give 'not in the list' error so we could use direct links for models? Even better would be to include them in the model, but i don't think that will happen soon.

**Comment by dhanushreddy291** [comment]
hey @fofr, it would be really amazing if you can record a video/or a blog, showing how to deploy 1-2 workflows from: https://openart.ai/workflows/all

It would be really very helpful, currently something or other fails and getting new errors.

**Comment by fofr** [comment]
I have something coming really soon that will let you do this from a civit or HF link

**Comment by fofr** [comment]
Ok, I've shipped a new feature that lets you upload:

- checkpoints
- loras
- embeddings
- controlnets
- animatediff motion models and loras

You need to use HuggingFace or CivitAI urls

https://replicate.com/fofr/any-comfyui-workflow/train

Check the training logs to see what filenames to use in your workflow JSON. For example:

```
Downloading from HuggingFace:
...
Size of the tar file: 217.88 MB
====================================
When using your new model, use these filenames in your JSON workflow:
araminta_k_midsommar_cartoon.safetensors
```

**Comment by promeG** [comment]
> Im also having an issue with this.
> 
> I put aniverse_thxEd14Pruned.safetensors inside comfyui/models/checkpoints before making the cog, and i removed the .safetensors and model dir dockerignore entries. But Weights_downloader complains they are not on the list.
> 
> Edit: Some useful information for anyone bumping into this.
> 
> **Custom SD Checkpoints**
> 
> * Place them in the correct models folder in the comfyui folder in the cog folder.
> * Edit .dockerignore, and comment out the ignores for safetensors and ckpts
> * Edit .dockerignore, and comment out the ignores for ComfyUI/models
> * Add the full name of the checkpoint you just added, to 'weights.json' file in the correct format.

In addition to the steps above, please run 'sudo cog build --no-cache' to create a new cog image containing new models.
